django_blog/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name='signup'),
    url(r'^login/$',views.login_view,name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
]

django_blog/articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'article'

urlpatterns = [
    url(r'^$',views.articles_list, name='list'),
    url(r'^create/$',views.create_view,name='create'),
    url(r'^(?P<slug>[\w-]+)/$',views.article_details, name='detail')
]

django_blog/django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$',views.about),
    url(r'^$',article_views.articles_list,name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django_blog/accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

django_blog/articles/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumbnail = models.ImageField(default='default.png',blank=True)
    author = models.ForeignKey(User,default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

django_blog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','slug','body','thumbnail']

django_blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        UCform = UserCreationForm(request.POST)
        if UCform.is_valid():
            # login
            user = UCform.save()
            login(request,user)
            return redirect('article:list')
    else:
        UCform = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':UCform})

def login_view(request):
    if request.method == 'POST':
        Aform = AuthenticationForm(data=request.POST)
        if Aform.is_valid():
            #login
            user = Aform.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('article:list')
    else:
        Aform = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':Aform})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('article:list')

django_blog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def articles_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/articles_list.html',{'articles': articles})

def article_details(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_details.html',{'article' : article})

@login_required(login_url="/accounts/login/")
def create_view(request):
    if request.method == 'POST':
        Newform = forms.CreateArticle(request.POST,request.FILES)
        if Newform.is_valid():
            # saving form to db
            instance = Newform.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('article:list')
    else:
        Newform = forms.CreateArticle()
    return render(request,'articles/create.html',{'form':Newform})

django_blog/django_blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
    #return HttpResponse('This is the about page, under construction')
    return render(request,'about.html')

def homepage(request):
    #return HttpResponse('This is the homepage, under construction')
    return render(request,'homepage.html')

django_blog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Log In</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {%csrf_token%}
  {{form}}
  {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
  {% endif %}
  <input type="submit" value="Login">
</form>
{%endblock%}

django_blog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Signup page</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
  {%csrf_token%}
  {{ form }}
  <input type="submit" value="Signup">
</form>
{% endblock %}

django_blog/articles/templates/articles/article_details.html
{% extends 'base_layout.html' %}

{%block content%}
<div class="article-detail">
  <div class="article">
    <img src="{{article.thumbnail.url}}" alt="dp"/>
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>
{%endblock%}

django_blog/articles/templates/articles/articles_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div>
<h1>Articles</h1>
  <br>
    <h2>Articles making it to the top</h2>
    <br><br>
    <div class="articles">
      {% for article in articles %}
        <div class="article">
          <h2><a href="{% url 'article:detail' slug=article.slug %}">{{article.title}}</a></h2>
          <p>{{article.snippet}}</p>
          <p>{{article.date}}</p>
        </div>
        <br><br>
      {% endfor %}
    </div>
</div>
{% endblock %}

django_blog/articles/templates/articles/create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
  <h2>Create a New Article</h2>
  <form class="site-form" action="{% url 'article:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create">
  </form>
</div>
<script type="text/javascript" src="/static/slugify.js"></script>
{% endblock %}

django_blog/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <header class="header">
      <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"/></a></h1>
        <nav>
          <ul>
          {% if user.is_authenticated %}
            <li>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit">LOGOUT</button>
              </form>
            </li>
            <li><a href="{% url 'article:create' %}" class="highlight">NEW ARTICLE</a></li>
           {% else %}
              <li><a href="{% url 'accounts:login' %}">LOGIN</a></li>
              <li><a href="{% url 'accounts:signup' %}">SIGNUP</a></li>
           {% endif %}
          </ul>
        </nav>
    </header>
    <div class="wrapper">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

django_blog/templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<div>
  <h1>Homepage</h1>
  <br><br>
  <h3>This is the homepage</h3>
</div>
{% endblock %}